Repository PyPlanet/PyPlanet, pull requests merged in 2021-02, with the labels that each got.

#1012 update support for xbox/ps4 controllers
  pyplanet/apps/core/pyplanet/templates/controller.Script.Txt
Labels: Enhancement

#1037 [Client] Proper Update XMLRPC.Scripted TMNext
  pyplanet/core/gbx/client.py
Labels: Enhancement, G:MP, G:TM, P:High

#1068 [FEATURE] Add support for UI properties in TM2020
  .appveyor.yml
  pyplanet/apps/contrib/currentcps/__init__.py
  pyplanet/apps/contrib/info/__init__.py
  pyplanet/apps/contrib/live_rankings/__init__.py
  pyplanet/apps/contrib/sector_times/__init__.py
  pyplanet/apps/core/pyplanet/app.py
  pyplanet/core/ui/ui_properties.py
Labels: App, Core, G:TM, P:Critical
